version: '3.8'

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=postgres
    ports:
      - 5434:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
  
  smartwey_webapi:
    image: vitaliytyu/smartway_webapi:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=postgres; Port=5432; User Id=postgres; Password=root; Database=SmartWayFiles;
    ports:
      - 5001:80
    depends_on:
      - postgres

volumes:
  pgdata:
